name: playstation_app_clone_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  html: ^0.15.3
  http: ^0.13.6
  mysql1: ^0.20.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path_provider: ^2.0.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatars/
    - assets/images/games/
    - assets/images/trophies/
    - assets/images/other/
    - assets/chat_messages.txt

